import Link from "next/link";
import type { Overview } from "@/lib/tracking/dashboard";
import type { DashLang } from "@/lib/tracking/copy";
import type { outcomeSummary, serverToolSummary } from "@/lib/tracking/server-ingest";

type Metric = { label: string; count: number | null; status: string; description: string; href: string; action: string };

export default function OverviewMetrics({ lang, days, domain, overview, browserActive, logsActive, toolsActive, outcomeConfigured, remoteConfigured, outcomes, remoteTools, ingestIssues }: {
  lang: DashLang; days: number; domain: string; overview: Overview;
  browserActive: boolean; logsActive: boolean; toolsActive: boolean; outcomeConfigured: boolean; remoteConfigured: boolean;
  outcomes: ReturnType<typeof outcomeSummary>; remoteTools: ReturnType<typeof serverToolSummary>; ingestIssues: number;
}) {
  const de = lang === "de", base = `/app/${encodeURIComponent(domain)}`, docs = de ? "/de/docs" : "/docs";
  const t = overview.totals, previous = overview.previous;
  const n = (value: number) => value.toLocaleString(de ? "de-DE" : "en-GB");
  const observed = de ? "Im Zeitraum beobachtet" : "Observed in this period";
  const trend = (current: number, before: number) => before > 0
    ? `${current >= before ? "+" : ""}${Math.round((current - before) / before * 100)}% ${de ? "zum Vorzeitraum" : "vs previous period"}`
    : current > 0 ? (de ? "Keine Beobachtungen im Vorzeitraum" : "No observations in previous period") : (de ? "Keine Beobachtungen im Zeitraum" : "No observations in period");
  const detail = de ? "Details ansehen" : "View details";
  const setup = de ? "Einrichtung ansehen" : "View setup";
  const groups: { title: string; description: string; metrics: Metric[] }[] = [
    { title: de ? "Besuche & Abrufe" : "Visits & fetches", description: de ? "Welche KI-Quellen auf deine Website verweisen und welche Crawler Inhalte abrufen." : "Which AI sources refer traffic to your website and which crawlers fetch content.", metrics: [
      { label: de ? "KI-Referrals" : "AI referrals", count: t.referrals || browserActive ? t.referrals : null, status: t.referrals || browserActive ? trend(t.referrals, previous.referrals) : (de ? "Keine Browserdaten im Zeitraum" : "No browser data in period"), description: de ? "Seitenaufrufe mit erkanntem KI-Referrer oder UTM-Signal, etwa ChatGPT. Keine Anzahl einzelner Personen oder Gespräche." : "Page observations with a recognized AI referrer or UTM signal, such as ChatGPT. Not a count of people or conversations.", href: `${base}/agents`, action: detail },
      { label: de ? "IP-bestätigte Abrufe" : "IP-confirmed fetches", count: t.verifiedFetches || logsActive ? t.verifiedFetches : null, status: t.verifiedFetches ? trend(t.verifiedFetches, previous.verifiedFetches) : logsActive ? observed : (de ? "Keine aktuelle Log-Quelle" : "No fresh log source"), description: de ? "Erfolgreiche HTML-Abrufe, deren Crawler-Identität per IP-Abgleich bestätigt wurde. Zeigt den Zugriff, keine Erwähnung in einer KI-Antwort." : "Successful HTML fetches with a crawler identity confirmed by IP matching. Evidence of access, not of a mention in an AI answer.", href: logsActive || t.verifiedFetches ? `${base}/pages#access-attempts` : `${de ? "/de" : ""}/guides/${de ? "welche-ki-crawler-lesen-meine-seiten" : "which-ai-crawlers-read-my-pages"}`, action: logsActive || t.verifiedFetches ? detail : setup },
      { label: de ? "Historische Abruf-Claims" : "Legacy fetch claims", count: t.fetches, status: de ? "Historisch · Identität unbestätigt" : "Historical · identity unverified", description: de ? "Ältere Signale mit Crawler-Kennung, ohne heutigen Identitätsnachweis. Separat lesen; sie zählen nicht als IP-bestätigte Abrufe." : "Older signals carrying a crawler name without current identity evidence. Read separately; these are not IP-confirmed fetches.", href: `${base}/agents`, action: detail },
    ] },
    { title: de ? "Tool-Nutzung" : "Tool activity", description: de ? "Welche Funktionen aufgerufen werden. Browser-Tools und Remote MCP haben eigene Datenquellen." : "Which functions are called. Browser tools and remote MCP use separate data sources.", metrics: [
      { label: de ? "Browser-Toolaufrufe" : "Browser tool calls", count: t.calls || toolsActive ? t.calls : null, status: t.calls ? trend(t.calls, previous.calls) : toolsActive ? observed : (de ? "Noch keine Tool-Messung belegt" : "No tool measurement established yet"), description: de ? "Erfasste Aufrufe instrumentierter WebMCP-Tools im Browser. Ein Aufruf allein beweist weder einen KI-Akteur noch einen erfolgreichen Abschluss." : "Recorded calls to instrumented WebMCP tools in the browser. A call alone proves neither an AI actor nor a successful outcome.", href: `${base}/tools`, action: detail },
      { label: de ? "Remote-MCP-Aufrufe" : "Remote MCP calls", count: remoteTools.reports ? remoteTools.counted : null, status: remoteTools.reports ? `${n(remoteTools.counted)} / ${n(remoteTools.reports)} ${de ? "Servermeldungen gezählt" : "server reports counted"}` : remoteConfigured ? (de ? "Zugang eingerichtet · keine Meldung" : "Credentials configured · no reports") : (de ? "Server-Anbindung fehlt" : "Server integration not configured"), description: de ? "Vom MCP-Server gemeldete Aufrufe. Benötigt eine eigene Server-Anbindung; das Browser-Snippet erfasst diese Aufrufe nicht." : "Calls reported by your MCP server. Requires a server integration; the browser snippet does not collect these calls.", href: `${docs}#server-outcomes`, action: setup },
      { label: de ? "Geschätzte tägliche Tool-Sessions" : "Estimated daily tool sessions", count: t.sessions || t.calls || toolsActive ? t.sessions : null, status: de ? "Tagessummen · Schätzung" : "Daily totals · estimate", description: de ? "Tool-Aktivität, pro Tag über Adress- und Browserklassen-Hashes gruppiert. Mehrere Personen können zusammenfallen, eine Person an mehreren Tagen zählen." : "Tool activity grouped each day using address and browser-class hashes. Several people may merge, and one person may count on several days.", href: `${base}/tools`, action: detail },
    ] },
    { title: de ? "Ziele & Ergebnisse" : "Goals & outcomes", description: de ? "Vom Zielversuch bis zum Serverbeleg: Was wurde versucht, was bestätigt, was bleibt offen?" : "From goal attempt to server receipt: what was attempted, confirmed, or remains unresolved?", metrics: [
      { label: de ? "Zielversuche" : "Goal attempts", count: t.goalAttempts || null, status: t.goalAttempts ? trend(t.goalAttempts, previous.goalAttempts) : (de ? "Noch keine Zielversuche empfangen" : "No goal attempts received yet"), description: de ? "Im Browser gemeldete Versuche, ein definiertes Ziel zu erreichen, etwa eine Anfrage. Noch kein Beleg für eine gespeicherte Anfrage oder Buchung." : "Browser-reported attempts to complete a defined goal, such as an inquiry. Not yet evidence of a saved inquiry or booking.", href: `${docs}#server-outcomes`, action: setup },
      { label: de ? "Serverbestätigte Abschlüsse" : "Server confirmed outcomes", count: outcomes.reports ? outcomes.confirmed : null, status: outcomes.reports ? `${n(outcomes.confirmed)} / ${n(outcomes.reports)} ${de ? "Serverbelege bestätigt" : "server receipts confirmed"}` : outcomeConfigured ? (de ? "Zugang eingerichtet · kein Beleg" : "Credentials configured · no receipts") : (de ? "Server-Anbindung fehlt" : "Server integration not configured"), description: de ? "Anfragen oder Buchungen, deren Speicherung dein Server bestätigt. Ein bestätigtes Ergebnis beweist allein noch keinen KI-Ursprung." : "Inquiries or bookings whose creation your server confirms. A confirmed outcome alone does not prove AI attribution.", href: `${docs}#server-outcomes`, action: setup },
      { label: de ? "Zielversuche ohne Bestätigung" : "Attempts without confirmation", count: t.goalAttempts ? Math.max(0, t.goalAttempts - outcomes.linkedGoalAttempts) : null, status: t.goalAttempts ? `${n(t.goalAttempts)} ${de ? "Browser-Zielversuche als Basis" : "browser goal attempts as basis"}` : (de ? "Keine Zielversuche als Basis" : "No goal attempts as a basis"), description: de ? "Zielversuche ohne verknüpften bestätigten Serverbeleg. Möglich sind ein offener Versuch oder eine fehlende Verknüpfung – nicht automatisch ein Fehler." : "Goal attempts without a linked confirmed server receipt. This may be an unfinished attempt or a missing link, not necessarily a failure.", href: `${docs}#server-outcomes`, action: detail },
    ] },
  ];
  return <div className="overview-metrics">
    <header className="metrics-intro"><div><p className="eyebrow">{de ? "Deine Messwerte" : "Your measurements"}</p><h2>{de ? "Was passiert auf deiner Website?" : "What happens on your website?"}</h2></div><span className="metric-period">{days} {de ? "Tage" : "days"}</span></header>
    <p className="metrics-key">{de ? "0 = Datenquelle vorhanden, kein passendes Ereignis gezählt. — = Messung oder Vergleichsbasis fehlt. Alle Werte gelten für den angezeigten Zeitraum." : "0 = a data source is present, with no matching event counted. — = measurement or a comparison basis is missing. All values apply to the displayed period."}</p>
    {groups.map(group => <section className="metric-group" key={group.title} aria-label={group.title}>
      <header><h3>{group.title}</h3><p>{group.description}</p></header>
      <div className="metric-grid">{group.metrics.map(m => <article className="metric-card" key={m.label}>
        <h4>{m.label}</h4><p className={`metric-value${m.count === null ? " is-missing" : ""}`}>{m.count === null ? "—" : n(m.count)}</p>
        <p className="metric-status">{m.status}</p><p className="metric-description">{m.description}</p>
        <Link href={m.href} className="metric-action">{m.action} →</Link>
      </article>)}</div>
    </section>)}
    <details className="metric-notes"><summary>{de ? "Zählweise, ältere Zielsignale & Datenlücken" : "Counting rules, legacy goal signals & data gaps"}</summary>
      <p><strong>{de ? "Unbestätigte Zielsignale" : "Unverified goal signals"}: {n(t.conversions)}.</strong> {de ? "Ältere Conversion-Meldungen ohne Serverbeleg. Diese Zahl ist kein Umsatz und kein bestätigter Abschluss." : "Legacy conversion reports without a server receipt. This is not revenue or a confirmed outcome."}</p>
      <p>{de ? `${n(outcomes.agentReported)} bestätigte Abschlüsse mit serverseitig gemeldetem Agenten; ${n(outcomes.actorUnknown)} mit unbekanntem Akteur. Browser-Versuche und Serverbelege haben unterschiedliche Bezugsgrößen und ergeben keine gemeinsame Conversion-Rate.` : `${n(outcomes.agentReported)} confirmed outcomes with a server-reported agent; ${n(outcomes.actorUnknown)} with an unknown actor. Browser attempts and server receipts use different bases and do not produce a combined conversion rate.`}</p>
      <p>{de ? "Tageswerte nutzen Europe/Berlin; Servermeldungen ein rollierendes Zeitfenster. Unvollständige Erfassung kann Vergleiche verzerren. Session-Hashes wechseln täglich; sie zählen keine eindeutigen Menschen oder Agenten. Einzelereignisse werden nach 90 Tagen gelöscht, Tageszähler können bleiben." : "Daily counts use Europe/Berlin; server reports use a rolling window. Incomplete collection can distort comparisons. Session hashes change daily and do not count unique people or agents. Individual events are deleted after 90 days; daily totals may remain."}</p>
    </details>
    {ingestIssues > 0 && <p className="metrics-warning" role="status">{de ? `${n(ingestIssues)} Hinweise auf verworfene oder begrenzte Datenpakete. Die Werte können unvollständig sein.` : `${n(ingestIssues)} signals of rejected or limited data batches. Counts may be incomplete.`} <Link href={`${base}/insights`}>Insights →</Link></p>}
  </div>;
}
