import type { Guide } from "@/lib/guides";

/** Long-form hub articles. Keep both lists in the same order for hreflang. */
export const SEO_GUIDES_EN: Guide[] = [
  {
    slug: "ai-agent-traffic-website-measurement-guide",
    question: "How do you measure AI agent traffic to your website?",
    title: "AI agent traffic: a practical measurement guide",
    summary: "Measure three separate signals: people who arrive from an AI assistant, automated requests that fetch your pages, and tool actions an agent performs on the site. Use page analytics for identifiable referrals, server access logs for crawlers, and explicit events for tool calls and completed goals. Keep the three counts separate: a fetch is not a click, and neither proves a citation.",
    sections: [
      { h: "Start with the question behind the number", p: [
        "A search for AI agent traffic can mean several things. A marketer wants to know whether ChatGPT sends visitors. A publisher wants to know which crawlers read articles. A developer wants to see whether an assistant calls a WebMCP tool and completes a booking. These are different events with different collection methods. If a dashboard adds them into one traffic number, the result looks impressive but cannot guide a decision.",
        "Write down the decision first: which landing page to improve, which bot to allow, or which tool error to fix. Then choose the signal that answers it. The [short guide to agentic visitors](/guides/what-counts-as-an-agentic-visitor) explains the three categories; this article shows how to measure them together without confusing them."
      ] },
      { h: "1. Measure visits referred by assistants", p: [
        "When a person clicks a link in an assistant, their browser may send a referrer such as chatgpt.com or perplexity.ai. Some links also carry a campaign parameter such as utm_source. Record the referring host, landing page, date and any relevant conversion. Classify that visit as an AI referral, which still represents a person visiting your site. It does not mean an autonomous agent used the page.",
        "The referrer is not guaranteed. Apps, privacy settings and redirects can remove it. A missing referrer therefore becomes Direct or another source; no analytics product can infer the missing origin with certainty. Report identifiable AI referrals as observed clicks, not as the total number of times an assistant mentioned you. [Plausible now provides an AI Assistants channel](https://plausible.io/docs/top-referrers), so it can measure this layer without a custom referrer list. GA4 can also report the underlying sources; the useful setup depends on your channel grouping and reports.",
        "For this layer, compare landing pages and outcomes. If one guide receives ten identifiable ChatGPT visits and two signups, that is more useful than a bot request total. Review a few weeks of data before drawing conclusions: a newly launched site can have many zero days. See the [ChatGPT referral guide](/guides/see-chatgpt-referral-traffic) for the narrow setup."
      ] },
      { h: "2. Read server logs for crawlers and live fetchers", p: [
        "Most named crawlers request HTML without executing the JavaScript analytics tag. Their requests appear in the web server or CDN log instead. Collect timestamp, path, response status, user-agent string and network address temporarily for verification. Group requests by crawler family and purpose: broad crawling for training, search indexing, or a user-initiated fetch are not equivalent. [Cloudflare's bot reference](https://developers.cloudflare.com/ai-crawl-control/reference/bots/) lists examples, including GPTBot, OAI-SearchBot and ChatGPT-User.",
        "Do not trust a user-agent string on its own. Anyone can claim to be GPTBot. Where an operator publishes address ranges or another verification method, check the request against it before describing the count as verified. Where verification is unavailable, label the count accordingly. Keep the verification rule and the date of the vendor list with your method, because those lists change. The [GPTBot verification guide](/guides/is-this-request-really-gptbot) covers the practical check.",
        "Look at paths and status codes, not only totals. A bot requesting a removed URL and receiving 404 is different from one successfully fetching your documentation. Short groups of requests can suggest a live research session, but the log does not reveal the user's prompt or guarantee that any page was cited. Some requests can be served from caches before they reach the origin, so an origin log may undercount activity at the edge."
      ] },
      { h: "3. Instrument actions and goals on the page", p: [
        "If your website exposes browser tools, record registrations and calls with a tool name, outcome, duration and error class. Mark a meaningful completion such as a confirmed booking or signup as a goal. A tool call is an attempt; a completed goal is a separate result. Avoid storing input values, personal details or entire prompts merely to produce aggregate analytics.",
        "A conventional web analytics tool can track a custom event if you add instrumentation. It does not automatically know that a browser model-context call took place, or whether an action was performed by an assistant. Agent Tracking's snippet observes supported on-page tools and goal markers. Check how attribution works before calling a conversion autonomous: a human who arrived from ChatGPT is an AI-referred visitor, while a browser agent operating a tool is another case. The [WebMCP analytics guide](/guides/analytics-for-webmcp-tools) explains the tool layer."
      ] },
      { h: "A repeatable setup for a small site", p: [
        "First, put a regular analytics tool on the site if you need the full picture of human visitors. In Agent Tracking, create the site and add the deferred snippet to every public page. Verify that a known assistant referral appears when it occurs and that ordinary human visits are not reported as bots. Second, import one day of access logs, then automate the import. Inspect a few raw lines and confirm that the displayed path and verified status match the log. Third, if you publish WebMCP tools, call one in a test environment and confirm its result appears. Finally, mark one real outcome as a goal and test it end to end.",
        "The software is [open source on GitHub](https://github.com/shufflethis/agent-tracking) under AGPL-3.0 and can run on your own server. The hosted Free plan currently covers one site, 10,000 agent events per month and a 30-day dashboard window; larger plans have different limits. Self-hosting avoids a software subscription but still requires a server and maintenance. The [documentation](/docs) provides the installation and API details."
      ] },
      { h: "Build a report that can drive action", p: [
        "Make separate weekly lines for identifiable AI referrals, verified crawler fetches, unverified claims, live fetches, tool calls, tool success rate and goal completions. For each, show the previous period and the top affected pages. Keep the definitions beside the chart. A rising crawler count with flat referrals is an observation, not evidence that your content is failing; the crawler's purpose and the time lag matter.",
        "Pair the report with [Google Search Console](https://search.google.com/search-console/about) for indexed pages, impressions and clicks. Google now offers separate visibility reporting for its generative search features; those impressions are part of Search Console's overall performance data, so avoid adding the reports together as if they were independent visits. [Google's announcement](https://developers.google.com/search/blog/2026/06/gen-ai-performance-reports) describes the scope. Check a page that earns impressions but few clicks before publishing another near-duplicate article.",
        "A useful weekly action might be: update a page that gets search impressions but no clicks; repair a tool that fails on a required field; or investigate a spike of unverified bot claims. Record the change date, then compare the same metric over the following weeks. That is a measurement loop, not a promise that every change will increase AI referrals."
      ] },
      { h: "What this measurement cannot prove", p: [
        "A crawler fetch does not prove inclusion in training, a search answer or a citation. A person arriving with a ChatGPT referrer does not reveal the prompt or the exact answer they saw. A missing referrer does not prove there was no AI recommendation. A burst of fetched pages is a pattern to investigate, not a confirmed single question. And conversion attribution depends on the events you instrument and the signals the browser exposes.",
        "Use language that matches the evidence: fetched, referred, called, completed. If you need to know whether a specific assistant visibly cites a page, test that assistant's answer separately and record the result as a sample, because live answers vary by query, account, location and time. [Google's guidance for AI search](https://developers.google.com/search/docs/fundamentals/ai-optimization-guide) emphasizes useful original content and ordinary search fundamentals; it does not promise a ranking shortcut for a special file or schema."
      ] },
    ],
    faq: [
      { q: "Can Google Analytics or Plausible count AI traffic?", a: "They can count identifiable visits referred by AI assistants. Plausible has an AI Assistants channel. Neither a browser analytics tag nor an unconfigured custom event measures all crawler fetches or browser tool calls automatically." },
      { q: "Does a crawler request mean my page was cited?", a: "No. It proves that a request for the page occurred in the available log. Citation and click-through are separate observations." },
      { q: "What should a new site measure first?", a: "Confirm indexing and search impressions, then measure identifiable assistant referrals and verified bot requests separately. Add tool and goal events only if the site offers relevant actions." },
    ],
    related: ["can-google-analytics-track-ai-agents", "which-ai-crawlers-read-my-pages", "analytics-for-webmcp-tools"],
    updated: "2026-09-24",
  },
  {
    slug: "ai-traffic-outlook-2026-2027",
    question: "How will AI traffic to websites develop in 2026 and 2027?",
    title: "AI traffic outlook: what website owners can measure now",
    summary: "Expect more automated page retrieval and more ways for assistants to act, but do not equate that with more human visits. The useful outlook separates crawler requests, clicks from assistants, visibility in AI search, and completed actions. Published network-wide trends describe the market; your own logs and referral data tell you whether they apply to your website.",
    sections: [
      { h: "Four trends that must not become one forecast", p: [
        "AI traffic is an umbrella term. A training crawler reading a thousand pages, a search assistant retrieving one product page, a person clicking a citation, and a browser agent booking an appointment all generate different traces. A rise in one does not predict an equal rise in the others. For a website owner, the questions are whether pages remain discoverable, whether assistants send relevant people, and whether an agent can complete a useful action.",
        "This article is an outlook as of September 2026, not a promise of a particular growth rate. Cloudflare's [2025 Radar review](https://blog.cloudflare.com/radar-2025-year-in-review/) reported a strong rise in user-action crawling on its network and large, variable crawl-to-refer ratios by platform. Those figures cover Cloudflare-observed traffic, not every site or industry. They give a reason to measure your own baseline, not a conversion forecast for a new domain."
      ] },
      { h: "Scenario 1: more machine requests, few additional visits", p: [
        "In this scenario, automated systems fetch more HTML to index, retrieve or use content, while human click-through remains small. This can happen when an assistant answers a question directly, when the fetched page is only one of several candidates, or when a crawler is collecting material for a purpose unrelated to immediate referrals. An origin server may also see only part of the activity if a CDN cache serves requests first.",
        "Watch verified requests by operator, path and purpose alongside identifiable assistant referrals. A useful ratio is verified HTML fetches divided by referred human landings for the same operator and period. Label it clearly: it is not a conversion rate and cannot prove that a given fetch caused a given click. Cloudflare uses a similar [crawl-to-refer measure](https://blog.cloudflare.com/ai-search-crawl-refer-ratio-on-radar/) at network scale and notes that it can swing sharply when referrals are sparse.",
        "For a young website, one click more or less can make a ratio jump dramatically. Publish raw counts with the ratio, use weekly or monthly windows and avoid ranking platforms by a metric based on a handful of visits. If a bot requests your documentation repeatedly but never sends clicks, first ask whether those documents answer questions completely and whether visitors would have a reason to follow a link."
      ] },
      { h: "Scenario 2: assistant referrals grow on specific pages", p: [
        "Another plausible path is modest overall AI referrals concentrated on a few pages: original research, product specifications, comparison tables and practical documentation. An assistant may link to a page because the reader needs the original detail or a next step. This is an editorial hypothesis to test, not a guaranteed ranking formula. Google says valuable, non-commodity content and standard search accessibility remain its core advice for generative search. [Read the primary guidance](https://developers.google.com/search/docs/fundamentals/ai-optimization-guide).",
        "Measure by landing page, referring assistant and outcome. Keep Google Search Console impressions and clicks beside your on-site referral report, but do not add them together. Google's [generative search reports](https://developers.google.com/search/blog/2026/06/gen-ai-performance-reports) show visibility in its own AI features; third-party assistant referrals are a different dataset. Review pages with impressions but no clicks before writing another article for a nearly identical query.",
        "A content strategy can improve the chance that a page is useful: answer the question early, name definitions, show a real method, link to primary evidence and keep the date current. It cannot force an assistant to cite the page, and a crawler fetch alone cannot tell you whether it did. The [measurement guide](/guides/ai-agent-traffic-website-measurement-guide) explains the evidence levels."
      ] },
      { h: "Scenario 3: agents perform more actions", p: [
        "Some assistants already navigate pages, fill forms and call browser-exposed tools. As implementations mature, a business may see more attempted searches, availability checks or bookings without an equivalent increase in conventional page views. Whether this happens on your site depends on the tasks you expose, client support and how reliably the action works. An action attempted is not an action completed.",
        "Measure tool registrations, calls, failures and completed goals separately. For example, a quote tool called twenty times with five validation errors and two confirmed quote submissions suggests a product problem you can investigate. The count says nothing about revenue unless you join it to your own business records. The [WebMCP analytics guide](/guides/analytics-for-webmcp-tools) explains the event layer, and the [goal guide](/guides/see-whether-ai-agents-buy-on-your-site) describes completion measurement.",
        "Keep human AI referrals distinct from autonomous actions. A person who follows a ChatGPT link and buys is commercially valuable, but the purchase was still made by a person. Calling both cases agent purchases inflates the story and makes product decisions worse."
      ] },
      { h: "What the first-party baseline should contain", p: [
        "For each week, record: Google search impressions and clicks; identifiable AI-referred visits by assistant; verified and unverified HTML requests by crawler; top requested and landed pages; tool calls; and completed goals. Note changes to bot rules, site architecture and content on the same timeline. Use a four-week view once there are enough observations, and show the raw counts whenever a percentage is quoted.",
        "For agenttracking.co itself, the September 2026 Search Console sample is early: brand variants dominate impressions and most relevant non-brand questions have only a few impressions each. A single click cannot establish a stable click-through rate. The sensible first target is to make existing intent pages clearer and easier to find, then wait for a few weeks of comparable data. An [open-source installation](/docs) can collect the on-site and log signals, while Search Console supplies search visibility.",
        "Do not publish customer benchmarks until the sample is large enough, the site mix is described and owners have allowed aggregate reporting. A public dashboard for one domain is a case study, not a market average. If you publish an index later, state the number of domains, selection method, period, exclusions and whether the counts come from origin logs or CDN logs."
      ] },
      { h: "A practical quarterly decision loop", p: [
        "Month one is about collection quality: confirm that an actual assistant referrer is classified correctly, bot verification matches the current operator lists, and a real goal event only fires after completion. Month two is about content and product changes: improve one page with relevant impressions, and fix one tool or form failure. Month three is about comparing the same signals over time, with any seasonality or campaign noted. This creates evidence without claiming attribution you do not have.",
        "If crawl requests grow and clicks stay flat, inspect purpose and the pages fetched. If impressions grow but clicks stay flat, inspect the page title and answer quality. If tool calls grow but goals stay flat, inspect failures and the final step. If assistant referrals grow, compare their landing pages and conversion outcomes with other channels. Each branch leads to a concrete next action; none requires a generic forecast about all AI traffic.",
        "The likely direction is a web with more machine reading and more agent actions. The uncertain part is how much qualified human traffic each site receives. Keep that uncertainty visible in every chart and revisit this outlook when first-party data make a stronger conclusion possible."
      ] },
    ],
    faq: [
      { q: "Will more AI crawler traffic bring more visitors?", a: "It may, but the relationship is neither direct nor guaranteed. Report crawler requests and identifiable referred visits separately." },
      { q: "Is a crawl-to-refer ratio a conversion rate?", a: "No. It compares counts from the same operator over a period; it cannot connect one fetch to one click." },
      { q: "How often should this outlook be updated?", a: "Review source claims quarterly, and update the site's own trend data monthly once the sample is meaningful." },
    ],
    related: ["ai-agent-traffic-website-measurement-guide", "how-much-ai-bot-traffic-does-a-website-get", "which-pages-do-ai-assistants-cite"],
    updated: "2026-09-24",
  },
  {
    slug: "open-source-ai-agent-analytics-self-hosting",
    question: "Is there a free, open-source way to track AI agents on a website?",
    title: "Open-source AI agent analytics: Free plan and self-hosting",
    summary: "Agent Tracking is AGPL-3.0 open-source software that you can run on your own server. Its hosted service also has a Free plan with one site, 10,000 agent events per month and a 30-day dashboard window. Free software does not eliminate server or maintenance costs, and a free hosted plan has limits. Choose the deployment based on the data you need and who will operate it.",
    sections: [
      { h: "What open source means here", p: [
        "The application's source code is [public on GitHub](https://github.com/shufflethis/agent-tracking) under the AGPL-3.0-only license. You can inspect the browser snippet, event ingestion, bot classification, log import and dashboard code. You can also run a copy on infrastructure you control. The license carries obligations when you offer a modified version as a network service; read the [license text](https://github.com/shufflethis/agent-tracking/blob/main/LICENSE) for the exact terms and seek qualified advice if you are planning a redistributed product.",
        "Open source is useful for a measurement product because the data path matters. You can check which fields the snippet sends, how crawler verification works and how long raw events remain. That is stronger evidence than a privacy slogan alone. It does not mean every deployment is automatically compliant with every local rule: configuration, notices, server access and operational practices remain the deployer's responsibility.",
        "A public repository also lets a team test an update before deploying it. The trade-off is that self-hosters become responsible for updates, backups, TLS, access control and monitoring. If nobody on the team owns those tasks, a hosted account may be simpler even when the software itself has no license fee."
      ] },
      { h: "What the hosted Free plan includes", p: [
        "The current Free plan allows one site, 10,000 agent events in a calendar month and 30 days of dashboard history. Ordinary human page views do not count against that agent-event limit. Raw event retention is separate from the dashboard window; consult the current [documentation](/docs) and account screen before making a long-term plan. Paid Pro and Agency tiers exist for more sites, volume and history. Do not describe the whole hosted service as permanently free or without limits.",
        "A small site can use the Free plan to learn whether assistants send identifiable referrals, which named bots reach its pages, and whether on-page tools are called. Crawler measurement needs a log import in addition to the script because many bots never execute JavaScript. The setup should be tested on the site's real traffic before you use a chart in a public report. The [complete measurement guide](/guides/ai-agent-traffic-website-measurement-guide) walks through each source.",
        "When you evaluate the free tier, estimate the number of agent events rather than total visits. A documentation site heavily crawled by bots may have a different event profile from a small brochure site. Decide what dashboard history your team actually needs. If your reports require a full year in the application, compare that requirement with the current plan limits before starting."
      ] },
      { h: "What self-hosting involves", p: [
        "The repository includes a Docker setup and instructions for running the Next.js application with a SQLite data file. Put a TLS-terminating reverse proxy in front of it, set the site origin and mail configuration, and give the data file persistent storage. Review the environment example rather than copying the public service's legal identity or contact details into your own installation. Then add your site's domain, install the snippet and verify the first event.",
        "A production setup needs routine backups of the SQLite file, access to logs for crawler import, a way to deliver login email and a repeatable update process. Test a restore, not only a backup job. Limit access to the application and its data file. These are ordinary server responsibilities, but they represent real labor and hosting cost. The cloud service takes on much of that operation in exchange for its plan limits and terms.",
        "If your site sits behind a CDN, remember that an origin access log may omit requests answered from the CDN cache or blocked at the edge. Importing that log still measures what reached your server, which may be enough for your question. For an edge-level count, use the CDN's own metrics as well. Do not compare the two totals without explaining their different coverage."
      ] },
      { h: "The data you can actually measure", p: [
        "The on-page snippet records identifiable assistant referrals, supported browser tool calls and marked goals. A server log import adds bot requests and verification where operators publish address ranges. These are separate categories. Neither a request nor a referral reveals a person's prompt; a bot request does not prove a citation. Keep the labels precise in any exported report. [Plausible's AI Assistants channel](https://plausible.io/docs/top-referrers) already handles the referral layer for many sites, while a bot audit at the edge can handle crawler activity. Choose Agent Tracking when joining those layers with tool and goal data is useful.",
        "The product records the page path rather than a full query string and aims to avoid storing visitor network addresses. Verify those claims against the code and your own deployment configuration before putting them in a privacy notice. A self-hosted copy also changes who operates the server and who has access to the data. The [privacy page](/privacy) describes the hosted service, not automatically every fork or private installation.",
        "If all you need is ChatGPT-referred human visits, your existing web analytics may already answer the question. If you need crawler counts only, a log parser can suffice. The value of a dedicated agent analytics installation grows when the team needs the sequence from discovery through on-page action and a completed goal."
      ] },
      { h: "A decision checklist", p: [
        "Use the hosted Free plan when you want to test one site quickly and its limits fit your traffic. Self-host when infrastructure control and inspectable operation are essential and you have someone to maintain it. Use a general web analytics tool beside either deployment for broad human visitor reporting. If you already use Cloudflare, review [AI Crawl Control](https://developers.cloudflare.com/ai-crawl-control/) for edge requests and rules; it serves a different position in the stack.",
        "Before choosing, answer five questions: Do you need verified crawler requests or only assistant referrals? Do you expose browser tools? What event volume and reporting window do you need? Where must the data live? Who maintains the application? Then run a one-week trial with a clear success criterion, such as identifying one crawler discrepancy or one failed tool call. A small, testable goal is more valuable than installing a dashboard and never acting on it.",
        "The software being open source is an invitation to verify the claims. The Free plan is an invitation to measure a real site without a payment card during the pilot. Neither is a substitute for deciding which question the measurement must answer."
      ] },
    ],
    faq: [
      { q: "Is the hosted service completely free?", a: "The hosted Free plan has one-site, event-volume and history limits. Paid plans provide higher limits. Self-hosting has no software subscription but does have infrastructure and maintenance costs." },
      { q: "Can the software run on my own server?", a: "Yes. The public repository includes a Docker setup and configuration example. The operator must provide TLS, persistent storage, mail, backups and updates." },
      { q: "Does the browser snippet alone count AI crawlers?", a: "No. Crawlers that do not run JavaScript require server or edge logs. The snippet handles browser-visible events." },
    ],
    related: ["ai-agent-traffic-website-measurement-guide", "can-google-analytics-track-ai-agents", "which-ai-crawlers-read-my-pages"],
    updated: "2026-09-24",
  },
];

export const SEO_GUIDES_DE: Guide[] = [
  {
    slug: "ki-agenten-traffic-website-messen-leitfaden",
    question: "Wie misst man KI-Agenten-Traffic auf einer Website?",
    title: "KI-Agenten-Traffic messen: ein praktischer Leitfaden",
    summary: "Trenne drei Signale: Menschen, die über einen KI-Assistenten kommen, automatische Abrufe deiner Seiten und Aktionen, die ein Agent auf der Website ausführt. Für erkennbare Referrals brauchst du Webanalyse, für Crawler Server-Logs und für Tool-Aufrufe eigene Events. Ein Abruf ist kein Klick und beweist auch kein Zitat.",
    sections: [
      { h: "Beginne mit der Entscheidung hinter der Zahl", p: [
        "Wer nach KI-Agenten-Traffic sucht, meint oft Verschiedenes. Marketing möchte wissen, ob ChatGPT Besucher schickt. Ein Verlag fragt, welche Crawler seine Artikel lesen. Entwickler möchten sehen, ob ein Assistent ein WebMCP-Tool aufruft und eine Buchung abschließt. Das sind unterschiedliche Ereignisse mit unterschiedlichen Datenquellen. Ein Dashboard, das sie zu einer einzigen großen Traffic-Zahl addiert, liefert keine brauchbare Handlungsgrundlage.",
        "Schreibe zuerst auf, welche Entscheidung ansteht: eine Einstiegsseite verbessern, einen Bot zulassen oder einen Tool-Fehler beheben. Dann wähle das passende Signal. Der [kurze Guide zu agentischen Besuchern](/de/guides/was-ist-ein-agentischer-besucher) definiert die Kategorien; dieser Leitfaden zeigt, wie du sie gemeinsam auswertest, ohne sie zu verwechseln."
      ] },
      { h: "1. Besucher aus KI-Assistenten messen", p: [
        "Klickt ein Mensch in einem Assistenten auf einen Link, kann sein Browser einen Referrer wie chatgpt.com oder perplexity.ai senden. Manche Links tragen zusätzlich einen Kampagnenparameter wie utm_source. Erfasse die Herkunftsdomain, die Einstiegsseite, das Datum und eine relevante Conversion. Dieser Besuch ist ein KI-Referral: Es besucht weiterhin ein Mensch die Website. Der Klick bedeutet nicht, dass ein autonomer Agent deine Seite bedient hat.",
        "Ein Referrer ist nicht garantiert. Apps, Datenschutzeinstellungen und Weiterleitungen können ihn entfernen. Der Besuch erscheint dann als Direct oder unter einer anderen Quelle. Kein Analytics-Werkzeug kann die fehlende Herkunft sicher rekonstruieren. Berichte erkennbare KI-Referrals als beobachtete Klicks und nicht als Zahl aller Erwähnungen durch Assistenten. [Plausible bietet inzwischen einen Kanal „AI Assistants“](https://plausible.io/docs/top-referrers); dafür muss man keine eigene Referrer-Liste pflegen. GA4 kann die Quellen ebenfalls auswerten; wie bequem das ist, hängt von der Konfiguration der Berichte ab.",
        "Vergleiche für diesen Bereich Einstiegsseiten und Ergebnisse. Zehn erkennbare ChatGPT-Besuche mit zwei Anmeldungen sagen mehr aus als eine große Bot-Zahl. Bei einer jungen Domain sind viele Tage mit null Klicks normal; bewerte mehrere Wochen zusammen. Der [Guide zu ChatGPT-Referrals](/de/guides/chatgpt-referral-traffic-sehen) zeigt die engere Auswertung."
      ] },
      { h: "2. Crawler und Live-Abrufe in Server-Logs sehen", p: [
        "Die meisten benannten Crawler fordern HTML an, ohne das JavaScript deiner Webanalyse auszuführen. Ihre Anfragen stehen deshalb im Server- oder CDN-Log. Für die Prüfung brauchst du vorübergehend Zeitpunkt, Pfad, HTTP-Status, User-Agent und Netzwerkadresse. Gruppiere nach Bot und Zweck: Training, Suchindex und Abruf im Auftrag eines Nutzers sind nicht dasselbe. [Cloudflares Bot-Referenz](https://developers.cloudflare.com/ai-crawl-control/reference/bots/) nennt unter anderem GPTBot, OAI-SearchBot und ChatGPT-User.",
        "Vertraue nicht allein auf den User-Agent. Jeder kann sich GPTBot nennen. Wenn der Betreiber IP-Bereiche oder ein anderes Prüfverfahren veröffentlicht, gleiche die Anfrage ab, bevor du sie als verifiziert ausweist. Wo eine Prüfung nicht möglich ist, kennzeichne die Zahl entsprechend. Halte Methode und Stand der Anbieterlisten fest, denn sie ändern sich. Der [Guide zur GPTBot-Prüfung](/de/guides/ist-diese-anfrage-wirklich-gptbot) erklärt den Ablauf.",
        "Prüfe auch Pfade und Statuscodes. Eine Anfrage an eine gelöschte URL mit 404 ist anders zu beurteilen als ein erfolgreicher Abruf deiner Dokumentation. Kurze Folgen mehrerer Abrufe können auf eine aktuelle Recherche hinweisen; das Log verrät aber weder die Frage des Nutzers noch, ob eine Seite zitiert wurde. Ein Origin-Log kann Anfragen übersehen, die bereits ein CDN-Cache beantwortet hat."
      ] },
      { h: "3. Tool-Aktionen und erreichte Ziele erfassen", p: [
        "Wenn deine Website Browser-Tools bereitstellt, erfasse Registrierung und Aufruf samt Tool-Namen, Ergebnis, Dauer und Fehlerklasse. Markiere einen tatsächlich abgeschlossenen Vorgang, etwa eine bestätigte Buchung, als Ziel. Ein Tool-Aufruf ist ein Versuch; ein erreichtes Ziel ist ein eigenes Ereignis. Eingabewerte, persönliche Angaben oder ganze Prompts brauchst du für aggregierte Kennzahlen gewöhnlich nicht.",
        "Klassische Webanalyse kann eigens instrumentierte Events zählen. Sie erkennt aber nicht automatisch einen Aufruf der Model-Context-API im Browser oder den Unterschied zwischen Assistent und Mensch. Das Snippet von Agent Tracking beobachtet unterstützte Tools und Zielmarker. Achte bei der Zuordnung darauf, einen Menschen mit ChatGPT-Referrer nicht als autonom handelnden Agenten zu bezeichnen. Der [WebMCP-Analytics-Guide](/de/guides/analytics-fuer-webmcp-tools) beschreibt die Tool-Ebene."
      ] },
      { h: "Ein wiederholbarer Aufbau für kleine Websites", p: [
        "Nutze zunächst ein gewöhnliches Analytics-Werkzeug, wenn du den gesamten menschlichen Traffic verstehen willst. Lege dann in Agent Tracking eine Website an und binde das verzögert ladende Snippet auf jeder öffentlichen Seite ein. Prüfe bei einem echten Referral, ob die Quelle korrekt erscheint, und stelle sicher, dass normale Besucher nicht als Bots gelten. Importiere anschließend einen Tag Access-Log und automatisiere erst danach den Import. Vergleiche einige Rohzeilen mit angezeigtem Pfad und Verifikationsstatus. Wenn du WebMCP-Tools veröffentlichst, führe eines in einer Testumgebung aus. Markiere schließlich einen realen Abschluss als Ziel und teste den gesamten Ablauf.",
        "Die Software ist [auf GitHub quelloffen](https://github.com/shufflethis/agent-tracking), steht unter AGPL-3.0 und lässt sich auf einem eigenen Server betreiben. Der gehostete Free-Plan umfasst derzeit eine Website, 10.000 Agenten-Events pro Monat und 30 Tage Dashboard-Verlauf. Größere Pläne haben andere Grenzen. Selbsthosting spart ein Software-Abo, benötigt aber Server und Wartung. Die [Dokumentation](/de/docs) enthält Einrichtung und API."
      ] },
      { h: "Ein Bericht, aus dem eine Maßnahme folgt", p: [
        "Zeige wöchentlich getrennte Zeilen für erkennbare KI-Referrals, verifizierte Crawler-Abrufe, unverifizierte Bot-Behauptungen, Live-Abrufe, Tool-Aufrufe, Erfolgsquote der Tools und abgeschlossene Ziele. Ergänze Vorperiode und wichtigste betroffene Seiten. Schreibe die Definitionen direkt zum Diagramm. Steigende Crawler-Zahlen bei gleichbleibenden Referrals sind zunächst eine Beobachtung, kein Beweis für schlechte Inhalte; Zweck und Zeitversatz der Abrufe spielen eine Rolle.",
        "Verbinde den Bericht mit der [Google Search Console](https://search.google.com/search-console/about): Dort siehst du indexierte Seiten, Impressionen und Klicks. Google stellt inzwischen eine eigene Ansicht zur Sichtbarkeit in generativen Suchfunktionen bereit. Diese Impressionen sind bereits Teil der allgemeinen Leistungsdaten und dürfen nicht wie zusätzliche Besuche addiert werden. [Google erklärt den Bericht hier](https://developers.google.com/search/blog/2026/06/gen-ai-performance-reports). Prüfe eine Seite mit Impressionen und wenig Klicks, bevor du einen fast gleichen neuen Artikel veröffentlichst.",
        "Eine konkrete Wochenmaßnahme kann sein, den Titel einer oft eingeblendeten, selten geklickten Seite zu verbessern, einen Fehler bei einem Pflichtfeld zu beheben oder ungewöhnlich viele unverifizierte Bot-Anfragen zu untersuchen. Notiere das Änderungsdatum und vergleiche danach dieselbe Kennzahl. Das ist ein Messkreislauf, kein Versprechen für mehr Referrals nach jeder Änderung."
      ] },
      { h: "Was die Messung nicht beweisen kann", p: [
        "Ein Crawler-Abruf beweist weder die Nutzung im Training noch eine Erwähnung oder ein Zitat. Ein ChatGPT-Referrer verrät weder den Prompt noch die genaue Antwort. Ein fehlender Referrer beweist nicht, dass keine KI-Empfehlung vorlag. Ein Burst ist ein Muster, keine bestätigte einzelne Nutzerfrage. Und die Zuordnung einer Conversion hängt von den eingebauten Events und verfügbaren Browser-Signalen ab.",
        "Verwende daher die passenden Wörter: abgerufen, vermittelt, aufgerufen, abgeschlossen. Willst du prüfen, ob ein Assistent eine bestimmte Seite sichtbar zitiert, teste die Antwort separat und dokumentiere sie als Stichprobe. Antworten variieren mit Frage, Konto, Ort und Zeitpunkt. [Googles Leitfaden für KI-Suche](https://developers.google.com/search/docs/fundamentals/ai-optimization-guide) empfiehlt originelle, hilfreiche Inhalte und solide Suchgrundlagen; er verspricht keinen speziellen GEO-Trick."
      ] },
    ],
    faq: [
      { q: "Können Google Analytics oder Plausible KI-Traffic messen?", a: "Sie können erkennbare Besuche aus KI-Assistenten zählen. Plausible hat dafür einen eigenen Kanal. Ein Webanalyse-Script allein misst weder alle Crawler-Abrufe noch Browser-Tool-Aufrufe automatisch." },
      { q: "Bedeutet ein Crawler-Abruf, dass meine Seite zitiert wurde?", a: "Nein. Er belegt nur eine Anfrage, die im verfügbaren Log steht. Zitat und Klick sind gesonderte Beobachtungen." },
      { q: "Was sollte eine neue Website zuerst messen?", a: "Zuerst Indexierung und Suchimpressionen prüfen. Danach erkennbare KI-Referrals und verifizierte Bot-Anfragen getrennt erfassen. Tool- und Ziel-Events lohnen sich, wenn die Website entsprechende Aktionen anbietet." },
    ],
    related: ["kann-google-analytics-ki-agenten-messen", "welche-ki-crawler-lesen-meine-seiten", "analytics-fuer-webmcp-tools"],
    updated: "2026-09-24",
  },
  {
    slug: "ki-traffic-ausblick-2026-2027",
    question: "Wie wird sich KI-Traffic auf Websites 2026 und 2027 entwickeln?",
    title: "KI-Traffic-Ausblick: Was Website-Betreiber heute messen können",
    summary: "Mehr automatische Seitenabrufe und mehr Aktionen durch Assistenten sind plausibel. Daraus folgen nicht automatisch mehr menschliche Besuche. Ein brauchbarer Ausblick trennt Crawler-Anfragen, Klicks aus Assistenten, Sichtbarkeit in KI-Suche und abgeschlossene Aktionen. Marktweite Trends liefern Kontext; deine eigenen Logs und Referrals zeigen, was für deine Website gilt.",
    sections: [
      { h: "Vier Entwicklungen ergeben keine einzelne Prognose", p: [
        "KI-Traffic ist ein Sammelbegriff. Ein Trainings-Crawler, der tausend Seiten liest, ein Suchassistent, der ein Produkt abruft, ein Mensch, der auf ein Zitat klickt, und ein Browser-Agent, der einen Termin bucht, hinterlassen unterschiedliche Spuren. Ein Anstieg der einen Größe sagt keinen gleich großen Anstieg der anderen voraus. Für Betreiber zählen drei Fragen: Bleiben Seiten auffindbar? Schicken Assistenten passende Menschen? Können Agenten eine nützliche Aktion abschließen?",
        "Dieser Text beschreibt den Stand im September 2026, keine garantierte Wachstumsrate. Cloudflare meldete im [Radar-Rückblick für 2025](https://blog.cloudflare.com/radar-2025-year-in-review/) einen deutlichen Anstieg nutzergesteuerter Crawler-Abrufe in seinem Netzwerk und große, wechselhafte Unterschiede zwischen Abrufen und Referrals je Plattform. Die Zahlen gelten für von Cloudflare beobachteten Traffic, nicht automatisch für jede Branche oder Domain. Sie begründen eine eigene Ausgangsmessung, keine Umsatzprognose."
      ] },
      { h: "Szenario 1: mehr Maschinenanfragen, kaum zusätzliche Besuche", p: [
        "Automatische Systeme können häufiger HTML laden, um Inhalte zu indexieren, zu suchen oder direkt zu verwenden, während Menschen nur selten auf die Quelle klicken. Ein Assistent beantwortet vielleicht schon die ganze Frage; vielleicht wurde die Seite lediglich als eine von mehreren Kandidatinnen geprüft; vielleicht hat ein Crawl gar keinen unmittelbaren Bezug zu Referrals. Auch ein Origin-Server sieht nicht jeden Abruf, wenn ein CDN vorher aus dem Cache antwortet.",
        "Vergleiche verifizierte Anfragen nach Betreiber, Pfad und Zweck mit erkennbaren Referrals aus denselben Assistenten. Eine Kennzahl kann sein: verifizierte HTML-Abrufe geteilt durch menschliche Landungen aus derselben Plattform im gleichen Zeitraum. Beschrifte sie sorgfältig. Sie ist keine Conversion-Rate und verbindet keinen einzelnen Abruf mit einem bestimmten Klick. Cloudflare nutzt ein ähnliches [Crawl-to-Refer-Verhältnis](https://blog.cloudflare.com/ai-search-crawl-refer-ratio-on-radar/) auf Netzwerkebene und weist auf starke Schwankungen bei wenigen Referrals hin.",
        "Auf einer jungen Website kann ein einziger zusätzlicher Klick das Verhältnis stark verändern. Zeige daher immer die absoluten Zahlen, verwende Wochen- oder Monatsfenster und sortiere Plattformen mit nur wenigen Besuchen nicht nach dieser Quote. Wenn ein Bot regelmäßig Dokumentation abruft, aber niemanden schickt, prüfe zuerst Zweck und betroffene Seiten. Ein oft geholter Artikel muss noch keinen Grund bieten, die Antwort zu verlassen und zur Quelle zu wechseln."
      ] },
      { h: "Szenario 2: Referrals konzentrieren sich auf wenige Seiten", p: [
        "Möglich ist auch, dass die Gesamtzahl der KI-Referrals langsam wächst, aber einige wenige Seiten besonders viele davon bekommen: eigene Forschung, genaue Produktspezifikationen, Vergleichstabellen oder praktische Dokumentation. Ein Assistent könnte auf solche Seiten verweisen, weil dort Details oder ein nächster Schritt liegen. Das ist eine redaktionelle Hypothese, keine garantierte Formel. Google empfiehlt für generative Suche vor allem wertvolle, eigenständige Inhalte und die üblichen Grundlagen der Auffindbarkeit. [Hier steht die Primärquelle](https://developers.google.com/search/docs/fundamentals/ai-optimization-guide).",
        "Miss nach Einstiegsseite, Assistent und Ergebnis. Stelle Impressionen und Klicks aus der Search Console neben deine Onsite-Referrals, addiere sie aber nicht. Googles [Berichte zu generativer Suche](https://developers.google.com/search/blog/2026/06/gen-ai-performance-reports) zeigen Sichtbarkeit in eigenen KI-Funktionen; Referrals von anderen Assistenten sind ein anderes Datenset. Prüfe Seiten mit Impressionen ohne Klicks, bevor du einen weiteren Artikel zur fast gleichen Frage schreibst.",
        "Gute Inhalte erhöhen die Chance, eine nützliche Quelle zu sein: Frage früh beantworten, Begriffe definieren, eine echte Methode zeigen, Primärquellen nennen und Angaben aktuell halten. Sie können kein Zitat erzwingen. Auch ein Abruf beweist kein Zitat. Der [Messleitfaden](/de/guides/ki-agenten-traffic-website-messen-leitfaden) ordnet die Evidenz ein."
      ] },
      { h: "Szenario 3: mehr Agentenaktionen auf Websites", p: [
        "Einige Assistenten können schon heute Seiten bedienen, Formulare ausfüllen und bereitgestellte Browser-Tools aufrufen. Mit reiferen Implementierungen könnten Suchvorgänge, Verfügbarkeitsabfragen oder Buchungsversuche zunehmen, ohne dass klassische Seitenaufrufe im gleichen Maß steigen. Ob das auf deiner Website geschieht, hängt von den angebotenen Aufgaben, der Unterstützung durch Clients und der Zuverlässigkeit der Schritte ab. Ein versuchter Vorgang ist noch kein abgeschlossener Vorgang.",
        "Erfasse Tool-Registrierungen, Aufrufe, Fehler und erreichte Ziele getrennt. Ein Angebots-Tool mit zwanzig Aufrufen, fünf Validierungsfehlern und zwei bestätigten Anfragen zeigt ein konkretes Problem, das sich untersuchen lässt. Die Zahl sagt ohne Verbindung zu deinen Geschäftsdaten nichts über Umsatz. Der [WebMCP-Guide](/de/guides/analytics-fuer-webmcp-tools) beschreibt diese Ereignisse; der [Ziel-Guide](/de/guides/sehen-ob-ki-agenten-auf-der-site-kaufen) erklärt den Abschluss.",
        "Halte menschliche KI-Referrals von autonomen Aktionen getrennt. Ein Mensch, der über ChatGPT kommt und kauft, ist wertvoll. Gekauft hat aber weiterhin ein Mensch. Beide Fälle als Agentenkäufe zu bezeichnen bläht die Aussage auf und verschlechtert Produktentscheidungen."
      ] },
      { h: "Welche eigene Ausgangsmessung nötig ist", p: [
        "Halte je Woche fest: Google-Impressionen und -Klicks, erkennbare KI-Referrals nach Assistent, verifizierte und unverifizierte HTML-Anfragen nach Bot, meist abgerufene und meist besuchte Seiten, Tool-Aufrufe und abgeschlossene Ziele. Markiere Änderungen an Bot-Regeln, Seitenstruktur und Inhalt auf derselben Zeitachse. Nutze eine Vier-Wochen-Sicht, sobald genug Beobachtungen vorliegen, und nenne zu jeder Prozentzahl auch die zugrunde liegenden Stückzahlen.",
        "Für agenttracking.co selbst ist die Search-Console-Stichprobe vom September 2026 noch jung. Varianten des Produktnamens dominieren die Impressionen; passende nicht markenbezogene Fragen haben meist nur wenige Impressionen. Ein einzelner Klick ergibt keine stabile Klickrate. Der erste sinnvolle Schritt ist, vorhandene Seiten mit klarer Suchintention zu verbessern und besser zu verlinken. Danach braucht es einige Wochen vergleichbarer Daten. Eine [Open-Source-Installation](/de/docs) kann die Onsite- und Log-Signale erfassen; die Search Console liefert die Suchsichtbarkeit.",
        "Veröffentliche Kunden-Benchmarks erst, wenn die Stichprobe ausreicht, der Mix der Websites beschrieben ist und Eigentümer einer aggregierten Veröffentlichung zugestimmt haben. Ein öffentliches Dashboard einer einzigen Domain ist eine Fallstudie, kein Marktdurchschnitt. Wenn später ein Index entsteht, nenne Anzahl der Domains, Auswahlmethode, Zeitraum, Ausschlüsse und Herkunft der Logs."
      ] },
      { h: "Ein Entscheidungszyklus für ein Quartal", p: [
        "Im ersten Monat geht es um Datenqualität: Wird ein echter Assistenten-Referrer korrekt eingeordnet? Stimmen Bot-Verifikation und aktuelle Anbieterlisten überein? Feuert ein Ziel-Event wirklich erst nach dem Abschluss? Im zweiten Monat verbesserst du eine Seite mit relevanten Impressionen und behebst einen Tool- oder Formularfehler. Im dritten vergleichst du dieselben Kennzahlen und notierst Saison, Kampagnen oder technische Änderungen. So entsteht Evidenz, ohne eine nicht messbare Ursache zu behaupten.",
        "Steigen Abrufe ohne Klicks, prüfe Zweck und betroffene Seiten. Steigen Impressionen ohne Klicks, prüfe Titel und Antwortqualität. Steigen Tool-Aufrufe ohne Ziele, untersuche Fehler und den letzten Schritt. Steigen Referrals, vergleiche ihre Einstiegsseiten und Ergebnisse mit anderen Kanälen. Jeder Fall führt zu einer konkreten Maßnahme; keiner braucht eine pauschale Prognose über den gesamten KI-Traffic.",
        "Wahrscheinlich wird das Web mehr maschinelles Lesen und mehr Agentenaktionen sehen. Wie viele qualifizierte Menschen daraus auf einer bestimmten Website ankommen, bleibt offen. Diese Unsicherheit sollte in jeder Grafik sichtbar sein. Aktualisiere den Ausblick, sobald eigene Daten eine stärkere Aussage erlauben."
      ] },
    ],
    faq: [
      { q: "Bringen mehr KI-Crawler auch mehr Besucher?", a: "Möglich, aber weder unmittelbar noch garantiert. Crawler-Anfragen und erkennbare Besucher aus Assistenten gehören in getrennte Reihen." },
      { q: "Ist die Crawl-to-Refer-Quote eine Conversion-Rate?", a: "Nein. Sie vergleicht Mengen derselben Plattform in einem Zeitraum und verbindet keinen einzelnen Abruf mit einem Klick." },
      { q: "Wie oft sollte der Ausblick aktualisiert werden?", a: "Prüfe externe Aussagen quartalsweise. Eigene Trends kannst du monatlich ergänzen, sobald die Stichprobe aussagekräftig ist." },
    ],
    related: ["ki-agenten-traffic-website-messen-leitfaden", "wie-viel-ki-bot-traffic-hat-eine-website", "welche-seiten-zitieren-ki-assistenten"],
    updated: "2026-09-24",
  },
  {
    slug: "open-source-ki-agenten-analytics-selbst-hosten",
    question: "Kann ich KI-Agenten auf meiner Website kostenlos und mit Open Source messen?",
    title: "Open-Source-Analytics für KI-Agenten: Free-Plan und Selbsthosting",
    summary: "Agent Tracking ist quelloffene Software unter AGPL-3.0, die du auf einem eigenen Server betreiben kannst. Der gehostete Dienst hat außerdem einen Free-Plan mit einer Website, 10.000 Agenten-Events pro Monat und 30 Tagen Dashboard-Verlauf. Quelloffene Software spart keine Server- und Wartungskosten; der gehostete Free-Plan hat Grenzen. Entscheide nach Datenbedarf und Betriebsaufwand.",
    sections: [
      { h: "Was Open Source hier bedeutet", p: [
        "Der Quellcode der Anwendung ist [auf GitHub öffentlich](https://github.com/shufflethis/agent-tracking) und steht unter AGPL-3.0-only. Du kannst das Browser-Snippet, die Event-Annahme, die Bot-Klassifikation, den Log-Import und den Dashboard-Code prüfen. Eine Kopie lässt sich auf eigener Infrastruktur betreiben. Wenn du eine veränderte Version als Netzwerkdienst anbietest, entstehen Pflichten aus der Lizenz. Lies dafür den [Lizenztext](https://github.com/shufflethis/agent-tracking/blob/main/LICENSE); für ein eigenes kommerzielles Angebot kann fachlicher Rat sinnvoll sein.",
        "Bei einem Messprodukt ist der offene Code besonders relevant: Der Datenweg lässt sich prüfen. Du kannst nachsehen, welche Felder das Snippet sendet, wie Crawler verifiziert werden und wie lange Rohereignisse bleiben. Das ist eine bessere Grundlage als ein Datenschutzslogan allein. Es macht aber nicht jede Installation automatisch rechtskonform. Konfiguration, Hinweise, Serverzugriff und betriebliche Abläufe liegen beim jeweiligen Betreiber.",
        "Ein öffentliches Repository erlaubt außerdem, Updates vor dem Einspielen zu testen. Dafür übernehmen Selbsthoster auch die Verantwortung für Backups, TLS, Zugriffsschutz, Überwachung und Aktualisierungen. Fehlt im Team jemand für diese Aufgaben, kann ein gehostetes Konto einfacher sein, obwohl der Quellcode selbst keine Lizenzgebühr kostet."
      ] },
      { h: "Was der gehostete Free-Plan enthält", p: [
        "Der aktuelle Free-Plan umfasst eine Website, 10.000 Agenten-Events je Kalendermonat und 30 Tage Dashboard-Verlauf. Normale menschliche Seitenaufrufe zählen nicht gegen diese Event-Grenze. Die Aufbewahrung von Rohereignissen ist vom sichtbaren Dashboard-Zeitraum zu unterscheiden; prüfe die aktuelle [Dokumentation](/de/docs) und dein Konto, bevor du langfristig planst. Pro und Agency haben höhere Grenzen. Bezeichne nicht den gesamten gehosteten Dienst als dauerhaft und unbegrenzt kostenlos.",
        "Eine kleine Website kann mit dem Free-Plan herausfinden, ob Assistenten erkennbare Besucher schicken, welche Bots die Seiten erreichen und ob Browser-Tools aufgerufen werden. Für Crawler brauchst du zusätzlich zum Script einen Log-Import, denn viele Bots führen kein JavaScript aus. Prüfe den Aufbau mit echtem Traffic, bevor du ein Diagramm öffentlich als Beleg zeigst. Der [vollständige Messleitfaden](/de/guides/ki-agenten-traffic-website-messen-leitfaden) erklärt jede Quelle.",
        "Schätze bei der Tarifwahl die Agenten-Events und nicht nur die Gesamtzahl der Besucher. Eine Dokumentationsseite, die häufig von Bots abgerufen wird, hat ein anderes Profil als eine kleine Unternehmensseite. Entscheide auch, wie viel Dashboard-Verlauf dein Team tatsächlich braucht. Wenn Berichte ein Jahr Daten in der Anwendung erfordern, vergleiche diese Anforderung vorab mit den aktuellen Plangrenzen."
      ] },
      { h: "Was zum Selbsthosting gehört", p: [
        "Das Repository enthält einen Docker-Aufbau und Anleitungen für die Next.js-Anwendung mit einer SQLite-Datei. Setze einen Reverse Proxy mit TLS davor, konfiguriere die eigene Site-Origin und den Mailversand, und speichere die Daten dauerhaft. Verwende die Beispiel-Umgebung als Ausgangspunkt. Übernimm dabei nicht versehentlich die Rechtstexte, Kontaktdaten oder Betreiberangaben des öffentlichen Dienstes. Lege dann deine Domain an, binde das Snippet ein und prüfe das erste Ereignis.",
        "Für den produktiven Betrieb brauchst du regelmäßige Backups der SQLite-Datei, Zugriff auf Logs für den Crawler-Import, Login-E-Mails und einen wiederholbaren Update-Prozess. Teste eine Wiederherstellung, nicht nur den Backup-Job. Begrenze den Zugriff auf Anwendung und Datendatei. Das sind gewöhnliche Serveraufgaben, kosten aber Zeit und Hosting-Gebühren. Der Cloud-Dienst übernimmt einen großen Teil davon im Rahmen seiner Tarife und Bedingungen.",
        "Wenn deine Website hinter einem CDN steht, fehlen im Origin-Log unter Umständen Anfragen, die das CDN aus dem Cache bedient oder am Netzrand blockiert hat. Der Log-Import misst dann immer noch, was deinen Server erreicht. Für eine vollständige Edge-Sicht verwende zusätzlich die CDN-Metriken. Vergleiche beide Summen nur mit einer Erklärung ihrer unterschiedlichen Abdeckung."
      ] },
      { h: "Welche Daten tatsächlich messbar sind", p: [
        "Das Seiten-Snippet erfasst erkennbare Referrals aus Assistenten, unterstützte Browser-Tool-Aufrufe und markierte Ziele. Ein Server-Log-Import ergänzt Bot-Anfragen und deren Prüfung, soweit Betreiber IP-Bereiche veröffentlichen. Diese Kategorien bleiben getrennt. Weder Anfrage noch Referral verraten den Prompt eines Menschen; ein Bot-Abruf beweist kein Zitat. Benenne die Ereignisse auch im Export genau. [Plausibles Kanal AI Assistants](https://plausible.io/docs/top-referrers) deckt die Referral-Ebene für viele Websites bereits ab. Ein Edge-Bot-Audit kann Crawler zählen. Agent Tracking wird interessant, wenn du diese Ebenen mit Tool- und Zieldaten verbinden willst.",
        "Das Produkt erfasst Seitenpfade statt vollständiger Query-Strings und soll keine Netzwerkadressen von Besuchern speichern. Prüfe solche Aussagen am Code und an deiner Konfiguration, bevor du sie in eigene Datenschutzhinweise übernimmst. Eine selbst gehostete Kopie verändert außerdem, wer den Server betreibt und wer Zugriff auf die Daten hat. Die [Datenschutzseite](/de/datenschutz) beschreibt den gehosteten Dienst, nicht automatisch jeden Fork.",
        "Wenn du ausschließlich Menschen messen willst, die von ChatGPT kommen, kann dein vorhandenes Webanalyse-Werkzeug genügen. Brauchst du nur Crawler-Zahlen, kann ein Log-Parser reichen. Eine eigene Agenten-Analytics-Installation lohnt sich besonders, wenn das Team den Weg vom Abruf über eine Aktion bis zum erreichten Ziel verstehen möchte."
      ] },
      { h: "Eine Entscheidung in fünf Fragen", p: [
        "Nutze den gehosteten Free-Plan, wenn du eine Website schnell testen willst und die Grenzen ausreichen. Hoste selbst, wenn Infrastrukturkontrolle wichtig ist und jemand den Betrieb übernimmt. Verwende für den gesamten menschlichen Traffic daneben gewöhnliche Webanalyse. Nutzt du bereits Cloudflare, prüfe [AI Crawl Control](https://developers.cloudflare.com/ai-crawl-control/) für Edge-Anfragen und Regeln; es sitzt an einer anderen Stelle im Aufbau.",
        "Kläre vor der Wahl fünf Punkte: Brauchst du verifizierte Crawler-Anfragen oder nur Assistenten-Referrals? Bietest du Browser-Tools an? Wie hoch sind Event-Volumen und gewünschter Berichtszeitraum? Wo müssen die Daten liegen? Wer wartet die Anwendung? Teste anschließend eine Woche mit einem konkreten Erfolgskriterium, etwa einem erkannten Bot-Unterschied oder einem gefundenen Tool-Fehler. Ein kleines, prüfbares Ziel ist wertvoller als ein Dashboard, auf das niemand reagiert.",
        "Die offene Software lädt dazu ein, Produktversprechen selbst zu prüfen. Der Free-Plan ermöglicht in der Pilotphase einen Test einer echten Website ohne Karte. Beides ersetzt nicht die Frage, welche Entscheidung die Messung ermöglichen soll."
      ] },
    ],
    faq: [
      { q: "Ist der gehostete Dienst vollständig kostenlos?", a: "Der Free-Plan hat Grenzen für Websites, Agenten-Events und Verlauf. Bezahlte Pläne haben höhere Grenzen. Selbsthosting hat keine Software-Abogebühr, verursacht aber Infrastruktur- und Wartungskosten." },
      { q: "Läuft die Software auf meinem eigenen Server?", a: "Ja. Das öffentliche Repository enthält Docker-Konfiguration und eine Beispiel-Umgebung. Der Betreiber stellt TLS, dauerhaften Speicher, Mailversand, Backups und Updates bereit." },
      { q: "Zählt das Browser-Snippet allein KI-Crawler?", a: "Nein. Crawler ohne JavaScript müssen über Server- oder Edge-Logs erfasst werden. Das Snippet misst Ereignisse, die im Browser sichtbar sind." },
    ],
    related: ["ki-agenten-traffic-website-messen-leitfaden", "kann-google-analytics-ki-agenten-messen", "welche-ki-crawler-lesen-meine-seiten"],
    updated: "2026-09-24",
  },
];
