import type { Guide } from "./guides";

export const WORKFLOW_GUIDES_EN: Guide[] = [
  {
    slug: "geo-aeo-measurement-playbook",
    question: "How do you turn GEO and AEO data into a checked website improvement?",
    title: "GEO and AEO measurement playbook: signals, fixes and evidence",
    summary: "Start with a business question, connect the relevant evidence source, investigate a specific failure, and retest the change. Keep AI visibility, website visits, crawler access and completed inquiries separate so the measurement supports a real decision.",
    updated: "2026-09-25",
    sections: [
      { h: "1. Choose the decision before the metric", p: ["Choose one question: Are assistants sending visitors to the intended page? Can a known crawler access the page? Does a supported tool complete its technical call? Was an inquiry actually created? Each question needs different evidence and leads to a different action.", "Write down the relevant URL or tool, the period, the owner and the result you want to check. A page with many crawler requests does not, by itself, deserve a rewrite. Use the [AI traffic measurement guide](/guides/ai-agent-traffic-website-measurement-guide) to choose a source."] },
      { h: "2. Keep visibility and website evidence separate", p: ["Brand mentions and citations require observing AI answers for a defined set of questions. Recognized referrals show visits attributed to an assistant. Origin logs show requests that reached your server. Browser and server tool telemetry show instrumented calls. Server receipts confirm reported business outcomes.", "These are not consecutive stages of one measured funnel unless you can actually link the records. In particular, dividing referrals by crawler requests does not give you an AI click-through rate. Read [which pages AI assistants cite](/guides/which-pages-do-ai-assistants-cite) before treating an access log as a visibility report."] },
      { h: "3. Connect the smallest useful measurement", p: ["Start with [ChatGPT referral attribution](/guides/see-chatgpt-referral-traffic) when visits are the question. Add [crawler logs](/guides/which-ai-crawlers-read-my-pages) when access is the question. Use [WebMCP tool analytics](/guides/analytics-for-webmcp-tools) for observed technical failures, and [server confirmation](/docs#server-outcomes) for inquiries or bookings.", "Check that the source is active before interpreting a zero. Record quota gaps, missing integrations and stale verification lists. An incomplete period is not a reliable baseline for a growth claim."] },
      { h: "4. Turn an observation into an investigation", p: ["Example, not customer data: a verified crawler receives HTTP 403 on a product page. Confirm which resource was requested, whether the restriction is intentional, and which access rule produced it. Only then decide whether to change the rule. A block on a private page may be correct.", "In Agent Tracking, Insights surfaces matching evidence rules and links to the relevant view. Tool errors are observations, not automatic root-cause diagnoses. A missing server receipt is an unknown outcome, not a lost lead. The suggested next step should reduce that uncertainty."] },
      { h: "5. Make one change and check the same task", p: ["Record the failure, proposed correction and test conditions. After the change, repeat the same prepared task. Keep URL, test mode and task comparable, and record the changed release or schema version. Use the [inquiry test and fix guide](/guides/test-ai-inquiry-flows-and-verify-fixes) for the current staging browser workflow.", "One failed run followed by one passed run is evidence about those two runs. It is not a production conversion uplift. More referrals after a content update are also not proof that the update caused the increase; coverage, seasonality and other changes may differ."] },
      { h: "6. Report a decision, evidence and the remaining uncertainty", p: ["A useful weekly report states what was observed, what you changed, what the retest showed, and what remains unknown. Include the measurement period and missing sources. If there is not enough activity for a trend, say so and choose a concrete task to test instead.", "Keep the checked change in the site's history so the next investigation can reuse it. [Protected findings and reports](/docs#private-workflow) let a team review the evidence. [Connect a website](/login) to begin with your own data."] },
    ],
    faq: [
      { q: "Can this prove that a GEO change increased revenue?", a: "A browser retest cannot establish revenue impact. That requires separately measured business outcomes and a comparison design that addresses other changes and uncertainty." },
      { q: "Do AI search features require a special SEO file?", a: "Google states that its existing SEO guidance applies to AI features and that no special AI text file or schema is required. A clear page, crawlable links and accessible content remain useful foundations." },
      { q: "What should a small site do before it has enough traffic?", a: "Confirm the measurement setup and test one prepared inquiry flow. Report the synthetic result separately from real visits and customer outcomes." },
    ],
    related: ["test-ai-inquiry-flows-and-verify-fixes", "ai-agent-traffic-website-measurement-guide", "see-chatgpt-referral-traffic"],
  },
  {
    slug: "test-ai-inquiry-flows-and-verify-fixes",
    question: "How do you test an inquiry flow and verify a website fix?",
    title: "Test inquiry flows and document fixes with browser evidence",
    summary: "Prepare an isolated staging form, record a baseline browser run, document the correction, and repeat the same task. Link the actual run IDs so the result can be reviewed. Agent Tracking currently runs a deterministic browser check, not an autonomous AI model test.",
    updated: "2026-09-25",
    sections: [
      { h: "Prepare an isolated inquiry path", p: ["Use an owned test or staging subdomain and a flow that cannot create a real booking or send a customer message. The current runner accepts test.your-domain and staging.your-domain over HTTPS. It blocks requests to other origins, so production integrations and external assets may not behave as they do on the live site.", "The form must have id agenttracking-test-form, data-agenttracking-test=true, fields named name, email and message, and a submit button. Set data-agenttracking-success=true on a result element only after the test inquiry is saved. The [task-test documentation](https://github.com/shufflethis/agent-tracking/blob/main/docs/task-tests.md) explains the current runner."] },
      { h: "Capture the baseline", p: ["Open Tests in the private workspace and run the prepared path. Save its run ID, result, error class and available release, tool and schema versions. A missing form marker is a failure of this test contract; it does not prove that an AI assistant could not find the live form.", "The runner uses fixed synthetic values and has a short execution deadline. It does not choose its own strategy or measure the behavior of ChatGPT, Claude or another external model."] },
      { h: "Document a specific correction", p: ["Create a finding linked to the baseline run. Describe the observed failure and the change, and assign responsibility if needed. Keep the proposed cause separate from what the test actually observed.", "For example: the staging endpoint saved the test inquiry but the page never exposed the success marker. Correcting that marker improves the test contract. Do not report this alone as a recovered customer inquiry."] },
      { h: "Run the same task after the change", p: ["Run the same task against the same URL and test mode. Record the new version, then link the before and after runs under Fix and retest. If test conditions differ, the comparison is shown as changed conditions rather than a controlled retest.", "A comparable failed-to-passed pair is retained in Insights under Findings & fixes. Each comparison contains one run per state. Repeat checks as needed, and keep any production outcome measurement separate."] },
      { h: "Confirm business outcomes separately", p: ["For real inquiries, integrate [server outcome receipts](/docs#server-outcomes) after a durable save. Use stable receipt IDs for retries and explicit links to the originating attempt or invocation where available. A browser click is not a confirmed inquiry.", "A server-reported actor and an independently verified crawler identity are different forms of evidence. Preserve those distinctions when presenting the result to a client."] },
      { h: "Share the result in context", p: ["Add the fix and retest to the finding and share the [protected site report](/docs#private-workflow). The recipient can review the original issue, correction, actual runs and remaining uncertainty. Public statistics do not expose these internal records.", "Use the [GEO/AEO measurement playbook](/guides/geo-aeo-measurement-playbook) to connect this check to a wider measurement plan. [Connect your website](/login) to start a private workspace."] },
    ],
    faq: [
      { q: "Does a passed test prove that ChatGPT can complete the task?", a: "No. The current test follows a fixed browser sequence on a prepared form. Testing an autonomous model would require a separate model-driven runner and explicit conditions." },
      { q: "Do synthetic runs count as real agent activity?", a: "No. Task runs are marked synthetic and remain separate from production activity metrics." },
      { q: "Can I run this on a live checkout?", a: "The current runner is restricted to an owned test or staging subdomain. Prepare an isolated flow without real orders, bookings or customer messages." },
    ],
    related: ["geo-aeo-measurement-playbook", "analytics-for-webmcp-tools", "see-whether-ai-agents-buy-on-your-site"],
  },
];

export const WORKFLOW_GUIDES_DE: Guide[] = [
  {
    slug: "geo-aeo-messung-playbook",
    question: "Wie wird aus GEO- und AEO-Daten eine überprüfte Website-Verbesserung?",
    title: "GEO- und AEO-Playbook: Signale, Korrekturen und Belege",
    summary: "Beginne mit einer Geschäftsfrage, verbinde die passende Datenquelle, untersuche einen konkreten Fehler und teste die Änderung nach. Halte KI-Sichtbarkeit, Website-Besuche, Crawler-Zugriffe und abgeschlossene Anfragen auseinander, damit die Messung eine echte Entscheidung unterstützt.",
    updated: "2026-09-25",
    sections: [
      { h: "1. Die Entscheidung vor der Kennzahl wählen", p: ["Wähle eine Frage: Schicken Assistenten Besucher auf die vorgesehene Seite? Kann ein bekannter Crawler die Seite abrufen? Wird ein unterstützter Tool-Aufruf technisch abgeschlossen? Wurde eine Anfrage tatsächlich angelegt? Jede Frage braucht andere Belege und führt zu einer anderen Handlung.", "Notiere URL oder Tool, Zeitraum, verantwortliche Person und das zu prüfende Ergebnis. Viele Crawler-Abrufe allein sind kein Grund, eine Seite umzuschreiben. Der [Leitfaden zur KI-Traffic-Messung](/de/guides/ki-agenten-traffic-website-messen-leitfaden) hilft bei der Wahl der Datenquelle."] },
      { h: "2. Sichtbarkeit und Website-Belege auseinanderhalten", p: ["Markenerwähnungen und Zitierungen erfordern die Beobachtung von KI-Antworten auf festgelegte Fragen. Erkannte Referrals zeigen einem Assistenten zugeordnete Besuche. Origin-Logs zeigen Anfragen, die deinen Server erreicht haben. Browser- und Server-Telemetrie zeigen instrumentierte Tool-Aufrufe. Serverbelege bestätigen gemeldete Geschäftsergebnisse.", "Diese Signale sind erst dann Stufen eines gemessenen Funnels, wenn sich die Datensätze tatsächlich verknüpfen lassen. Referrals geteilt durch Crawler-Abrufe ergeben keine KI-Klickrate. Lies den Guide zu [Zitierungen durch KI-Assistenten](/de/guides/welche-seiten-zitieren-ki-assistenten), bevor du ein Access-Log als Sichtbarkeitsbericht verwendest."] },
      { h: "3. Die kleinste nützliche Messung verbinden", p: ["Beginne mit der [Zuordnung von ChatGPT-Traffic](/de/guides/chatgpt-referral-traffic-sehen), wenn es um Besuche geht. Ergänze [Crawler-Logs](/de/guides/welche-ki-crawler-lesen-meine-seiten) für Zugriffsfragen. Nutze [WebMCP-Tool-Analytics](/de/guides/analytics-fuer-webmcp-tools) für beobachtete technische Fehler und [Serverbestätigungen](/de/docs#server-outcomes) für Anfragen oder Buchungen.", "Prüfe die Datenquelle, bevor du eine Null interpretierst. Halte Kontingentlücken, fehlende Integrationen und veraltete Verifikationslisten fest. Ein unvollständiger Zeitraum ist keine verlässliche Basis für eine Wachstumsaussage."] },
      { h: "4. Aus einer Beobachtung eine Untersuchung machen", p: ["Beispiel, keine Kundendaten: Ein verifizierter Crawler erhält auf einer Produktseite HTTP 403. Prüfe die angefragte Ressource, die Absicht der Sperre und die verantwortliche Zugriffsregel. Entscheide erst dann über eine Änderung. Eine Sperre auf einer privaten Seite kann richtig sein.", "Insights zeigt in Agent Tracking passende regelbasierte Hinweise und verlinkt die jeweilige Ansicht. Tool-Fehler sind Beobachtungen, keine automatische Ursachendiagnose. Ein fehlender Serverbeleg bedeutet einen unbekannten Ausgang, keinen verlorenen Lead. Der nächste Schritt sollte diese Unsicherheit verringern."] },
      { h: "5. Eine Änderung machen und dieselbe Aufgabe prüfen", p: ["Dokumentiere Fehler, Korrektur und Testbedingungen. Wiederhole nach der Änderung denselben vorbereiteten Ablauf. Halte URL, Testart und Aufgabe vergleichbar und notiere die geänderte Release- oder Schemaversion. Der Guide zum [Anfrage-Test mit Korrekturbeleg](/de/guides/ki-anfrageablauf-testen-und-korrekturen-belegen) beschreibt den aktuellen Browserablauf auf Staging.", "Ein gescheiterter und danach ein bestandener Lauf belegen diese beiden Tests. Sie sind kein Conversion-Uplift im Produktivbetrieb. Mehr Referrals nach einer Inhaltsänderung beweisen ebenfalls keine Ursache: Messabdeckung, Saisonalität und andere Änderungen können abweichen."] },
      { h: "6. Entscheidung, Belege und offene Fragen berichten", p: ["Ein nützlicher Wochenbericht nennt Beobachtung, Änderung, Nachtestergebnis und verbleibende Unsicherheit. Nenne Messzeitraum und fehlende Quellen. Reicht die Aktivität nicht für einen Trend, sage das und wähle stattdessen einen konkreten Testablauf.", "Bewahre die überprüfte Änderung im Website-Verlauf auf, damit die nächste Untersuchung darauf aufbauen kann. [Geschützte Befunde und Berichte](/de/docs#private-workflow) machen die Belege im Team prüfbar. [Verbinde eine Website](/login?lang=de), um mit eigenen Daten zu beginnen."] },
    ],
    faq: [
      { q: "Beweist das zusätzlichen Umsatz durch eine GEO-Änderung?", a: "Ein Browser-Nachtest belegt keine Umsatzwirkung. Dafür brauchst du gesondert gemessene Geschäftsergebnisse und einen Vergleich, der andere Änderungen und Unsicherheit berücksichtigt." },
      { q: "Brauchen KI-Suchfunktionen eine besondere SEO-Datei?", a: "Laut Google gelten die bestehenden SEO-Empfehlungen auch für KI-Funktionen; besondere KI-Textdateien oder spezielle strukturierte Daten sind nicht erforderlich. Verständliche Seiten, crawlbare Links und zugängliche Inhalte bleiben die Grundlage." },
      { q: "Was kann eine kleine Website ohne genügend Traffic tun?", a: "Prüfe die Messeinrichtung und einen vorbereiteten Anfrageablauf. Berichte das synthetische Ergebnis getrennt von echten Besuchen und Kundenergebnissen." },
    ],
    related: ["ki-anfrageablauf-testen-und-korrekturen-belegen", "ki-agenten-traffic-website-messen-leitfaden", "chatgpt-referral-traffic-sehen"],
  },
  {
    slug: "ki-anfrageablauf-testen-und-korrekturen-belegen",
    question: "Wie testest du einen Anfrageablauf und belegst eine Website-Korrektur?",
    title: "Anfrageabläufe testen und Korrekturen mit Browserbelegen dokumentieren",
    summary: "Bereite ein isoliertes Staging-Formular vor, erfasse einen Ausgangslauf, dokumentiere die Korrektur und wiederhole dieselbe Aufgabe. Verknüpfe die tatsächlichen Run-IDs, damit das Ergebnis prüfbar bleibt. Agent Tracking führt derzeit einen deterministischen Browser-Test aus, keinen autonomen KI-Modelltest.",
    updated: "2026-09-25",
    sections: [
      { h: "Einen isolierten Anfrageweg vorbereiten", p: ["Nutze eine eigene Test- oder Staging-Subdomain und einen Ablauf ohne echte Buchung oder Kundennachricht. Der aktuelle Runner akzeptiert test.deine-domain und staging.deine-domain über HTTPS. Er blockiert Requests zu anderen Origins; Produktivintegrationen und externe Ressourcen können sich deshalb anders verhalten als auf der Live-Website.", "Das Formular benötigt die ID agenttracking-test-form, data-agenttracking-test=true, Felder namens name, email und message sowie einen Submit-Button. Setze data-agenttracking-success=true an einem Ergebniselement erst nach dem Speichern der Testanfrage. Die [technische Testdokumentation auf Englisch](https://github.com/shufflethis/agent-tracking/blob/main/docs/task-tests.md) beschreibt den aktuellen Runner."] },
      { h: "Den Ausgangszustand erfassen", p: ["Öffne Tests im privaten Arbeitsbereich und starte den vorbereiteten Ablauf. Halte Run-ID, Ergebnis, Fehlerklasse und verfügbare Release-, Tool- und Schemaversionen fest. Ein fehlender Formularmarker verletzt die Bedingungen dieses Tests; er beweist nicht, dass ein KI-Assistent das echte Formular nicht finden könnte.", "Der Runner verwendet feste synthetische Werte und eine kurze Ausführungsfrist. Er wählt keine eigene Strategie und misst nicht das Verhalten von ChatGPT, Claude oder einem anderen externen Modell."] },
      { h: "Eine konkrete Korrektur dokumentieren", p: ["Lege einen mit dem Ausgangslauf verknüpften Befund an. Beschreibe beobachteten Fehler und Änderung und ordne bei Bedarf eine verantwortliche Person zu. Trenne die vermutete Ursache von dem, was der Test tatsächlich zeigt.", "Beispiel: Der Staging-Endpunkt speichert die Anfrage, aber die Seite zeigt keinen Erfolgsmarker. Die Marker-Korrektur verbessert den Testablauf. Berichte sie allein nicht als gerettete Kundenanfrage."] },
      { h: "Dieselbe Aufgabe nach der Änderung ausführen", p: ["Wiederhole dieselbe Aufgabe auf derselben URL mit derselben Testart. Notiere die neue Version und verknüpfe beide Läufe unter Korrektur und Nachtest. Abweichende Bedingungen werden als geänderte Testbedingungen gekennzeichnet.", "Ein vergleichbarer Wechsel von gescheitert zu bestanden bleibt unter Insights in den Erkenntnissen erhalten. Jeder Vergleich enthält einen Lauf pro Zustand. Wiederhole Prüfungen nach Bedarf und halte die Messung echter Geschäftsergebnisse getrennt."] },
      { h: "Geschäftsergebnisse gesondert bestätigen", p: ["Integriere für echte Anfragen [Serverbelege](/de/docs#server-outcomes) nach dem dauerhaften Speichern. Verwende stabile Beleg-IDs für Wiederholungen und explizite Verknüpfungen zum Versuch oder Aufruf, soweit vorhanden. Ein Browserklick ist keine bestätigte Anfrage.", "Ein vom Server gemeldeter Akteur und eine unabhängig verifizierte Crawler-Identität sind unterschiedliche Belegarten. Bewahre diese Unterscheidung auch im Kundenbericht."] },
      { h: "Das Ergebnis mit Kontext teilen", p: ["Ergänze Korrektur und Nachtest am Befund und teile den [geschützten Website-Bericht](/de/docs#private-workflow). Empfänger können Problem, Änderung, tatsächliche Läufe und offene Fragen nachvollziehen. Öffentliche Statistiken zeigen diese internen Fälle nicht.", "Das [GEO-/AEO-Playbook](/de/guides/geo-aeo-messung-playbook) ordnet die Prüfung in einen Messplan ein. [Verbinde deine Website](/login?lang=de), um einen privaten Arbeitsbereich zu starten."] },
    ],
    faq: [
      { q: "Beweist ein bestandener Test, dass ChatGPT die Aufgabe lösen kann?", a: "Nein. Der aktuelle Test folgt einem festen Browserablauf auf einem vorbereiteten Formular. Ein autonomer Modelltest würde einen gesonderten modellgesteuerten Runner und explizite Bedingungen benötigen." },
      { q: "Zählen synthetische Tests als echte Agentenaktivität?", a: "Nein. Aufgabenläufe sind als synthetisch markiert und bleiben von Produktivkennzahlen getrennt." },
      { q: "Kann ich damit einen echten Checkout testen?", a: "Der aktuelle Runner ist auf eine eigene Test- oder Staging-Subdomain beschränkt. Bereite einen isolierten Ablauf ohne echte Bestellungen, Buchungen oder Kundennachrichten vor." },
    ],
    related: ["geo-aeo-messung-playbook", "analytics-fuer-webmcp-tools", "sehen-ob-ki-agenten-auf-der-site-kaufen"],
  },
];

// Source links are rendered in the article body rather than only in machine-readable metadata.
for (const [guides, label] of [[WORKFLOW_GUIDES_EN, "Google's guidance on AI features and websites"], [WORKFLOW_GUIDES_DE, "Googles Hinweise zu KI-Funktionen und Websites"]] as const) {
  guides[0].sections[1].p.push(`[${label}](https://developers.google.com/search/docs/appearance/ai-features)`);
}
